import { describe, expect, it } from 'vitest';
import { automate, MODEL_DEFAULTS } from '../../src/gcode/Automator.js';
import { PRINTER_MODELS, automatorModelKey } from '../../src/models/PrinterModels.js';

// A minimal Bambu-style plate gcode with the end-gcode marker the Automator
// anchors on. Enough for a full transform round-trip without a real slice.
const SAMPLE_GCODE = [
    '; generated by test',
    'G28',
    'G90',
    'G1 X10 Y10 Z0.2 F3000',
    'G1 X50 Y50 E5 F1500',
    'M73 P100 R0',
    '; MACHINE_END_GCODE_START',
    'M400',
    'G1 Z100 F600',
    'M140 S0',
    '; EXECUTABLE_BLOCK_END',
].join('\n');

describe('Automator per-model sweep geometry', () => {
    for (const [model, geometry] of Object.entries(MODEL_DEFAULTS)) {
        it(`bakes ${model} sweep lanes and park position into the output`, () => {
            const { output, report } = automate(SAMPLE_GCODE, { printerModel: model, loopsN: 1 });

            expect(report.printerModel).toBe(model);
            // Sweep start + every lane + park must come from THIS model, not P1S.
            expect(output).toContain(`G1 X${geometry.sweepStartX} Y${geometry.sweepStartY} F${geometry.fTravel}`);
            for (const lane of geometry.sweepLanesX) {
                expect(output).toContain(`G1 X${lane} F${geometry.fTravel} ; move to lane X=${lane}`);
            }
            expect(output).toContain(`G1 X${geometry.parkX} Y${geometry.parkY} F${geometry.fTravel} ; park`);

            // Fans only fire on models that have them.
            if (geometry.hasAuxFan) {
                expect(output).toContain('M106 P2 S255');
            } else {
                expect(output).not.toContain('M106 P2 S255');
            }

            // Original end gcode is replaced, block framing preserved.
            expect(output).toContain('ANTIGRAVITY AUTOMATION START');
            expect(output).toContain('; EXECUTABLE_BLOCK_END');
        });
    }

    it('loops the transformed file N times without multiplying end gcode', () => {
        const { output } = automate(SAMPLE_GCODE, { printerModel: 'H2D', loopsN: 3 });
        expect(output.match(/=== LOOP \d OF 3 ===/g)).toHaveLength(3);
        expect(output.match(/ANTIGRAVITY AUTOMATION START/g)).toHaveLength(3);
    });

    it('every registry model resolves to geometry that stays inside its bed', () => {
        for (const model of PRINTER_MODELS) {
            const geometry = MODEL_DEFAULTS[automatorModelKey(model.name)];
            expect(geometry, model.name).toBeTruthy();
            expect(geometry.sweepStartX).toBeLessThanOrEqual(model.bed.x);
            expect(geometry.sweepStartY).toBeLessThanOrEqual(model.bed.y);
        }
    });
});
